title: IxVenture
description: Building something amazing with AI

# Repo-mode settings
url: ""
baseurl: ""

theme: minima

# Site version
version: 0.2.1

collections:
  projects:
    output: true
    permalink: /projects/:path/
  partnerships:
    output: true
    permalink: /partnerships/:path/
  operations:
    output: true
    permalink: /operations/:path/
  products:
    output: true
    permalink: /products/:path/
  about-us:
    output: true
    permalink: /about-us/:path/

# Ensure static images are included
include:
  - assets
  - version.json
